// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/kwseeker/kratos-gateway/echo/internal/biz"
	"github.com/kwseeker/kratos-gateway/echo/internal/conf"
	"github.com/kwseeker/kratos-gateway/echo/internal/data"
	"github.com/kwseeker/kratos-gateway/echo/internal/server"
	"github.com/kwseeker/kratos-gateway/echo/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	echoRepo := data.NewEchoRepo(dataData, logger)
	echoUsecase := biz.NewEchoUsecase(echoRepo, logger)
	echoService := service.NewEchoService(echoUsecase)
	grpcServer := server.NewGRPCServer(confServer, echoService, logger)
	httpServer := server.NewHTTPServer(confServer, echoService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
